deepseek-ai_deepseek-v4-flash:
  provider: openai-compatible
  key: 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
  url: https://integrate.api.nvidia.com/v1
  name: deepseek-ai/deepseek-v4-flash

qwen_qwen3.5-397b-a17b:
  provider: openai-compatible
  key: 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
  url: https://integrate.api.nvidia.com/v1
  name: qwen/qwen3.5-397b-a17b

qwen_qwen3-next-80b-a3b-instruct:
  provider: openai-compatible
  key: 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
  url: https://integrate.api.nvidia.com/v1
  name: qwen/qwen3-next-80b-a3b-instruct

mistralai_ministral-14b-instruct-2512:
  provider: openai-compatible
  key: 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
  url: https://integrate.api.nvidia.com/v1
  name: mistralai/ministral-14b-instruct-2512
